# Generated by Django 5.0.2 on 2024-05-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk', '0002_movie_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='kinopoisk/videos/movies/movie_files'),
        ),
    ]
